title: Programmation Python avancée
description: >-
  Cette page, associée au livre <em>Programmation Python avancée – Guide pour une pratique élégante et efficace</em> aux éditions Dunod (ISBN 978-2-10-081598-2), contient les ressources complémentaires et le code source des exemples présentés.
author: Xavier Olive
baseurl: "/python"
email: git@xoolive.org
repository: xoolive/python
lang: fr-FR
github_username: xoolive
twitter_username: x00live
google_analytics: "G-45F3WK484S"

theme: jekyll-theme-minimal

include: ["_pages", "_static"]

header_pages:
  - contents
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
