[project]
name = "python_web"
version = "0.1.0"
description = "Add a short description here"
authors = ["Xavier Olive <git@xoolive.org>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]

[dependencies]
python = ">=3.12.5,<3.13"
git = ">=2.46.0,<2.47"
numpy = ">=2.1.0,<2.2"
matplotlib = ">=3.9.2,<3.10"
scipy = ">=1.14.1,<1.15"
jupyterlab = ">=4.2.5,<4.3"
cartopy = ">=0.23.0,<0.24"
cartes = ">=0.8.0,<0.9"
pandas = ">=2.2.2,<2.3"
polars = ">=1.6.0,<1.7"
altair = ">=5.4.1,<5.5"
ipyleaflet = ">=0.19.2,<0.20"
mypy = ">=1.11.2,<1.12"
ruff = ">=0.6.2,<0.7"
xarray = ">=2024.7.0,<2024.8"
cfgrib = ">=0.9.14.0,<0.9.15"
satpy = ">=0.51.0,<0.52"
s3fs = ">=2024.9.0,<2024.10"
pycoast = ">=1.7.1,<1.8"
textual = ">=0.79.1,<0.80"
textual-dev = ">=1.6.1,<1.7"
sqlalchemy = ">=2.0.35,<2.1"
duckdb-engine = ">=0.13.1,<0.14"
cairosvg = ">=2.7.1,<2.8"
